"""init

Revision ID: 798cb5cfdf68
Revises: 
Create Date: 2026-09-10 19:50:03.439391
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '798cb5cfdf68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=True),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('trace_id', sa.String(length=80), nullable=True),
    sa.Column('result', sa.String(length=40), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_case_id'), 'audit_log', ['case_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('bnss_stage', sa.Enum('fir_registered', 'under_investigation', 'chargesheet_filed', 'trial', 'disposed', name='bnss_stage'), nullable=True),
    sa.Column('data_classification', sa.Enum('public', 'internal', 'confidential', 'restricted', 'highly_restricted', name='classification'), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_backup_manifests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('merkle_root', sa.String(length=64), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processed', 'failed', name='outbox_status'), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aggregate_id', 'aggregate_version', 'event_type', name='uq_outbox_idempotency')
    )
    op.create_index(op.f('ix_outbox_events_case_id'), 'outbox_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('CONSTABLE', 'INSPECTOR', 'ADMIN', name='user_role'), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('clearance', sa.Enum('public', 'internal', 'confidential', 'restricted', 'highly_restricted', name='clearance'), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('anomaly_confidence', sa.Float(), nullable=True),
    sa.Column('source_precision', sa.String(length=40), nullable=True),
    sa.Column('entity_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('evidence_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detector_name', sa.String(length=120), nullable=True),
    sa.Column('detector_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_case_id'), 'anomalies', ['case_id'], unique=False)
    op.create_table('break_glass_requests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_break_glass_requests_user_id'), 'break_glass_requests', ['user_id'], unique=False)
    op.create_table('case_graph_state',
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('graph_version', sa.Integer(), nullable=True),
    sa.Column('analytics_version', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('entities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_observation_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_case_id'), 'entities', ['case_id'], unique=False)
    op.create_index('ix_entities_case_type', 'entities', ['case_id', 'type'], unique=False)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('file_uri', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('prev_chain_hash', sa.String(length=64), nullable=True),
    sa.Column('chain_hash', sa.String(length=64), nullable=False),
    sa.Column('merkle_leaf_hash', sa.String(length=64), nullable=True),
    sa.Column('scan_result', sa.String(length=40), nullable=True),
    sa.Column('processing_status', sa.String(length=40), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index('ix_evidence_case_seq', 'evidence', ['case_id', 'sequence_number'], unique=False)
    op.create_table('firs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('fir_number', sa.String(length=80), nullable=False),
    sa.Column('police_station', sa.String(length=200), nullable=True),
    sa.Column('date_registered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bns_sections', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('complainant_ref', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firs_case_id'), 'firs', ['case_id'], unique=False)
    op.create_table('criminal_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('case_ref', sa.String(length=120), nullable=True),
    sa.Column('offense_type', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_document_id', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criminal_history_entity_id'), 'criminal_history', ['entity_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_document_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('text_span', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('normalized_value', sa.String(length=400), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=80), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('model_version', sa.String(length=60), nullable=True),
    sa.Column('algorithm_name', sa.String(length=120), nullable=True),
    sa.Column('algorithm_version', sa.String(length=60), nullable=True),
    sa.Column('prompt_version', sa.String(length=60), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_case_id'), 'observations', ['case_id'], unique=False)
    op.create_index(op.f('ix_observations_normalized_value'), 'observations', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_observations_source_document_id'), 'observations', ['source_document_id'], unique=False)
    op.create_table('predicted_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('target_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=60), nullable=True),
    sa.Column('algorithm_name', sa.String(length=120), nullable=True),
    sa.Column('algorithm_version', sa.String(length=60), nullable=True),
    sa.Column('graph_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predicted_links_case_id'), 'predicted_links', ['case_id'], unique=False)
    op.create_table('provenance',
    sa.Column('provenance_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=True),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('text_span', sa.Text(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_method', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('provenance_id')
    )
    op.create_index(op.f('ix_provenance_case_id'), 'provenance', ['case_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('target_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('relationship_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('source_observed', 'inferred', 'proposed', 'human_confirmed', 'disputed', 'rejected', 'superseded', 'expired', name='rel_status'), nullable=True),
    sa.Column('evidence_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('provenance_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurred_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurred_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=200), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.provenance_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rel_case_status', 'relationships', ['case_id', 'status'], unique=False)
    op.create_index(op.f('ix_relationships_case_id'), 'relationships', ['case_id'], unique=False)
    op.create_index(op.f('ix_relationships_source_id'), 'relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_id'), 'relationships', ['target_id'], unique=False)
    op.create_table('resolution_candidates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('entity_a_observation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('entity_b_observation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('resolution_confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=80), nullable=True),
    sa.Column('algorithm_name', sa.String(length=120), nullable=True),
    sa.Column('algorithm_version', sa.String(length=60), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='candidate_status'), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['entity_a_observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['entity_b_observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_candidates_case_id'), 'resolution_candidates', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolution_candidates_case_id'), table_name='resolution_candidates')
    op.drop_table('resolution_candidates')
    op.drop_index(op.f('ix_relationships_target_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_case_id'), table_name='relationships')
    op.drop_index('ix_rel_case_status', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_provenance_case_id'), table_name='provenance')
    op.drop_table('provenance')
    op.drop_index(op.f('ix_predicted_links_case_id'), table_name='predicted_links')
    op.drop_table('predicted_links')
    op.drop_index(op.f('ix_observations_source_document_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_normalized_value'), table_name='observations')
    op.drop_index(op.f('ix_observations_case_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_criminal_history_entity_id'), table_name='criminal_history')
    op.drop_table('criminal_history')
    op.drop_index(op.f('ix_firs_case_id'), table_name='firs')
    op.drop_table('firs')
    op.drop_index('ix_evidence_case_seq', table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index('ix_entities_case_type', table_name='entities')
    op.drop_index(op.f('ix_entities_case_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('case_graph_state')
    op.drop_index(op.f('ix_break_glass_requests_user_id'), table_name='break_glass_requests')
    op.drop_table('break_glass_requests')
    op.drop_index(op.f('ix_anomalies_case_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_case_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_table('evidence_backup_manifests')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_log_case_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
